### ISSUE TITLE
Display of Crypto

### ISSUE THREAD

**Issue by gitboej** [gitboej/capstone-project#2]
## Value proposition

As a user,
I want to see several crypto currencies
in order to get information about its current standing

## Description

![Screenshot 2023-04-27 at 09 31 43](https://user-images.githubusercontent.com/125680620/234794719-c1926e1c-5e41-4f20-8905-840bfb035776.png)

## Acceptance criteria

- [ ] the crypto currency is displayed in a card
- [ ] price is displayed correctly
- [ ] the header is displayed

## Tasks

- [ ] create a branch
- [ ] create a card component
- [ ] create a header component
- [ ] create a connection to the api
- [ ] fetch the api data and displayed it in the corresponding card

**Comment by NikRoe** [comment]
Hi Lars,

this looks very promising!

In your value proposition you should speak of several crypto currencies.

You mention displaying the price, however, this is not visible in your wireframe.
Please update your wireframe to also show where the price will be displayed.

And there is a button / an icon in the bottom right corner of your wireframe. What does this element do?
If it serves no purpose, please remove it from the wireframe.

**Comment by NikRoe** [comment]
Hi Lars,

you can use real values and don't need a placeholder for the price.
For Bitcoin it could be `25.930,85 €`.

Please update your wireframe accordingly and then you can proceed with your next user story 🙌
