### ISSUE TITLE
Fetching of data

### ISSUE THREAD

**Issue by gitboej** [gitboej/capstone-project#4]
## Value proposition

As a admin
I want to fetch the current values for all the crypto currencies
in order to display them correctly

## Description

![Screenshot 2023-05-23 at 15 56 23](https://github.com/gitboej/capstone-project/assets/125680620/13ce59c8-894b-4e35-aa78-0ed365ee55b7)

## Acceptance criteria

- [ ] the abbreviation is displayed
- [ ] the price is displayed

## Tasks

- [ ] create a branch
- [ ] fetch the API
- [ ] display the data

**Comment by antoniatandler** [comment]
LGTM 😎
